version: '3.8'

services:
  # Base de datos PostgreSQL 
  postgres-db:
    image: postgres:15-alpine
    container_name: discord_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discord_network

  # Backend de NestJS
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - discord_network

volumes:
  postgres_data:

networks:
  discord_network:
    driver: bridge
